### ISSUE TITLE
Derivatives problem

### ISSUE THREAD

**Issue by jdavidrcamacho** [jdavidrcamacho/mini-frame#7]
After this [derivatives_test.py](https://gist.github.com/jdavidrcamacho/e5a13a8e87ab4ec7c30bb93f2aa8643e) I'm not sure of anything anymore xD

**Comment by j-faria** [comment]
I think the "problem" is related to [this](https://en.wikipedia.org/wiki/Signed_zero).
Eat a Easter egg and don't worry :)
